<?php

namespace AppBundle\Repository;

/**
 * ArtistOwnershipRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtistOwnershipRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
