<?php

namespace AppBundle\Repository;

/**
 * Artist_UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Artist_UserRepository extends \Doctrine\ORM\EntityRepository
{
}
