<?php

namespace AppBundle\Repository;
use AppBundle\Entity\ContractArtist;
use AppBundle\Entity\User;

/**
 * CartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCurrentForFan(User $fan) {
        return $this->createQueryBuilder('c')
            ->where('c.user = :fan')
            ->andWhere('c.confirmed = 0')
            ->setParameter('fan', $fan)
            ->getQuery()
            ->getOneOrNullResult()
            ;
    }

    public function findWithUsersAndContracts() {
        return $this->createQueryBuilder('c')
            ->join('c.user', 'u')
            ->join('c.contracts', 'fc')
            ->addSelect('u')
            ->addSelect('fc')
            ->getQuery()
            ->getResult()
            ;
    }

    public function findOngoingForContract(ContractArtist $contract) {
        return $this->createQueryBuilder('c')
            ->join('c.contracts', 'fc')
            ->where('c.confirmed = 0')
            ->andWhere('fc.contractArtist = :contract')
            ->setParameter('contract', $contract)
            ->getQuery()
            ->getResult()
            ;
    }
}
