<?php

namespace AppBundle\Repository;
use AppBundle\Entity\User;

/**
 * CartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCurrentForFan(User $fan) {

        return $this->createQueryBuilder('c')
            ->where('c.user = :fan')
            ->andWhere('c.confirmed = 0')
            ->setParameter('fan', $fan)
            ->getQuery()
            ->getOneOrNullResult();

    }
}
