<?php

namespace AppBundle\Repository;
use AppBundle\Entity\ContractArtist;
use AppBundle\Entity\User;

/**
 * CartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartRepository extends \Doctrine\ORM\EntityRepository
{
    public function findConfirmedForUser(User $user) {
        return $this->createQueryBuilder('c')
            ->join('c.contracts', 'cf')
            ->orderBy('cf.date', 'desc')
            ->where('c.user = :user')
            ->andWhere('c.confirmed = 1')
            ->setParameter('user', $user)
            ->getQuery()
            ->getResult()
        ;
    }

    public function findCurrentForUser(User $user) {
        $result = $this->createQueryBuilder('c')
            ->where('c.user = :user')
            ->andWhere('c.confirmed = 0')
            ->orderBy('c.id', 'desc')
            ->setMaxResults(1)
            ->setParameter('user', $user)
            ->getQuery()
            ->getResult();

        if(is_array($result) && isset($result[0])) {
            return $result[0];
        }
        else {
            return null;
        }
    }

    public function findCurrentsForUser(User $user) {
        return $this->createQueryBuilder('c')
            ->where('c.user = :user')
            ->andWhere('c.confirmed = 0')
            ->orderBy('c.id', 'desc')
            ->setMaxResults(1)
            ->setParameter('user', $user)
            ->getQuery()
            ->getResult()
            ;
    }

    public function findWithUsersAndContracts() {
        return $this->createQueryBuilder('c')
            ->join('c.user', 'u')
            ->join('c.contracts', 'fc')
            ->addSelect('u')
            ->addSelect('fc')
            ->getQuery()
            ->getResult()
            ;
    }

    public function findOngoingForContract(ContractArtist $contract) {
        return $this->createQueryBuilder('c')
            ->join('c.contracts', 'fc')
            ->where('c.confirmed = 0')
            ->andWhere('fc.contractArtist = :contract')
            ->setParameter('contract', $contract)
            ->getQuery()
            ->getResult()
            ;
    }
}
