<?php

namespace AppBundle\Repository;

/**
 * ConsomableRewardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsomableRewardRepository extends \Doctrine\ORM\EntityRepository
{

}