<?php

namespace AppBundle\Repository;

/**
 * ContractFanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContractFanRepository extends \Doctrine\ORM\EntityRepository
{
}
