<?php

namespace AppBundle\Repository;

/**
 * ContractArtist_ArtistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContractArtist_ArtistRepository extends \Doctrine\ORM\EntityRepository
{
}
