<?php

namespace AppBundle\Repository;

/**
 * ContactPersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactPersonRepository extends \Doctrine\ORM\EntityRepository
{
}
