<?php

namespace AppBundle\Repository;

/**
 * ContractArtistPreferencesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContractArtistPossibilityRepository extends \Doctrine\ORM\EntityRepository
{
}
