<?php

namespace AppBundle\Repository;

use AppBundle\Entity\ContractArtist;
use AppBundle\Entity\User;

/**
 * ContractFanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContractFanRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * find the last contract fan of contract_artist event.
     * This contract fan will be rewarded of sponsorship invitation
     *
     * @param User $user
     * @param ContractArtist $contractArtist
     * @return mixed null or contract fan
     */
    public function findSponsorshipContractFanToReward(User $user, ContractArtist $contractArtist)
    {
        return $this->getEntityManager()->createQuery(
            'SELECT cf,ca,p,u
                  FROM AppBundle:ContractFan cf
                  LEFT JOIN cf.contractArtist ca
                  LEFT JOIN cf.payment p
                  LEFT JOIN p.user u
                  WHERE u.id = ?1
                  AND ca.id = ?2
                  ORDER BY cf.date DESC
                  ')
            ->setParameter(1, $user->getId())
            ->setParameter(2, $contractArtist->getId())
            ->setMaxResults(1)
            ->getOneOrNullResult();
    }
}
