<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Province;
use AppBundle\Entity\Step;

/**
 * HallRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HallRepository extends \Doctrine\ORM\EntityRepository
{
    public function findPotential(Step $step, Province $province = null) {
        $qb = $this->createQueryBuilder('h')
            ->where('h.visible = 1')
            ->andWhere('h.step = :step')
            ->setParameter('step', $step)
        ;

        if($province != null) {
            $qb->andWhere('h.province = :province')
            ->setParameter('province', $province);
        }

        return $qb->getQuery()->getResult();
    }

}
