<?php

namespace AppBundle\Repository;

/**
 * HallRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HallRepository extends \Doctrine\ORM\EntityRepository
{
}
