<?php

namespace AppBundle\Repository;

/**
 * InvitationRewardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvitationRewardRepository extends \Doctrine\ORM\EntityRepository
{

}