<?php

namespace AppBundle\Repository;

/**
 * ReductionRewardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReductionRewardRepository extends \Doctrine\ORM\EntityRepository
{

}