<?php
/**
 * Created by PhpStorm.
 * User: Jean-François Cochar
 * Date: 28/03/2018
 * Time: 15:00
 */

namespace AppBundle\Repository;

/**
 * RewardRestrictionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RewardRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllReward()
    {
        return $this->getEntityManager()->createQuery(
            'SELECT r, rt
                  FROM AppBundle:Reward r
                  LEFT JOIN r.translations rt
                  ')
            ->getResult();
    }
}