<?php

namespace AppBundle\Repository;

/**
 * RewardRestrictionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RewardRestrictionRepository extends \Doctrine\ORM\EntityRepository
{

}