<?php

namespace AppBundle\Repository;

/**
 * RewardTicketConsumption
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RewardTicketConsumption extends \Doctrine\ORM\EntityRepository
{
}
