<?php
/**
 * Created by PhpStorm.
 * User: Jean-François Cochar
 * Date: 28/03/2018
 * Time: 15:00
 */

namespace AppBundle\Repository;

/**
 * RewardRestrictionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RewardRepository extends \Doctrine\ORM\EntityRepository
{
    public function findNotDeletedRewards()
    {
        return $this->getEntityManager()->createQuery(
            'SELECT r, rt, rw
                  FROM AppBundle:Reward r
                  LEFT JOIN r.restrictions rw
                  LEFT JOIN r.translations rt
                  WHERE r.deletedAt IS NULL 
                  ')
            ->getResult();
    }

    public function getReward($id)
    {
        return $this->getEntityManager()->createQuery(
            'SELECT r, rt, rw
                  FROM AppBundle:Reward r
                  LEFT JOIN r.restrictions rw
                  LEFT JOIN r.translations rt
                  WHERE r.id = ?1
                  ')
            ->setParameter(1, $id)
            ->getSingleResult();
    }
}