<?php

namespace AppBundle\Repository;

/**
 * RewardRestrictionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RewardRestrictionRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Recovers the most recent confirmed concert
     *
     * @return mixed contract_artist
     */
    public function getMostRecentConfirmedConcert()
    {
        return $this->getEntityManager()->createQuery(
            'SELECT c, a
                  FROM AppBundle:ContractArtist c
                  LEFT JOIN c.artist a
                  WHERE c.successful = TRUE 
                  ORDER BY c.dateEnd DESC
                  ')
            ->setMaxResults(1)
            ->getSingleResult();
    }

    /**
     * get all restrictions order by name ASC
     *
     * @param $locale
     * @return array restriction_reward array
     */
    public function getAllRestrictionOrderByAsc($locale)
    {
        return $this->getEntityManager()->createQuery(
            'SELECT rr,r
                  FROM AppBundle:RewardRestriction rr
                  LEFT JOIN rr.rewards r
                  LEFT JOIN r.translations rt
                  LEFT JOIN rr.translations rrt
                  WHERE rrt.locale = :locale
                  ORDER BY rrt.name ASC
                  ')
            ->setParameter('locale', $locale)
            ->getResult();
    }
}