<?php

namespace AppBundle\Repository;

/**
 * SpecialAdvantageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecialAdvantageRepository extends \Doctrine\ORM\EntityRepository
{

    public function findCurrents() {
        return $this->createQueryBuilder('s')
            ->where('s.available = 1')
            ->andWhere('s.availableQuantity > 0')
            ->getQuery()
            ->getResult();
    }
}
