<?php

namespace AppBundle\Repository;

/**
 * SpecialPurchaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecialPurchaseRepository extends \Doctrine\ORM\EntityRepository
{
}
