<?php

namespace AppBundle\Repository;

/**
 * SpecialAdvantageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecialAdvantageRepository extends \Doctrine\ORM\EntityRepository
{
}
