<?php

namespace AppBundle\Repository;

/**
 * StepRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StepRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOrderedStepsWithoutPhases() {
        return $this->createQueryBuilder('s')
            ->join('s.phase', 'p')
            ->orderBy('p.num', 'asc')
            ->addOrderBy('s.num', 'asc')
            ->getQuery()
            ->getResult()
        ;
    }

}
