<?php

namespace AppBundle\Repository;

/**
 * StepTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StepTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
