<?php

namespace AppBundle\Repository;

/**
 * SuggestionTypeEnumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuggestionTypeEnumRepository extends \Doctrine\ORM\EntityRepository
{
}
