<?php
/**
 * Created by PhpStorm.
 * User: Jean-François Cochar
 * Date: 23/03/2018
 * Time: 16:00
 */

namespace AppBundle\Repository;

/**
 * User_RewardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class User_RewardRepository extends \Doctrine\ORM\EntityRepository
{

}