<?php

namespace XBundle\Repository;

/**
 * ChoiceOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChoiceOptionRepository extends \Doctrine\ORM\EntityRepository
{
}
