<?php

namespace XBundle\Repository;

/**
 * OptionProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OptionProductRepository extends \Doctrine\ORM\EntityRepository
{
}
