<?php

namespace XBundle\Repository;

use AppBundle\Entity\User;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{

    public function baseQueryBuilder() {
        return $this->createQueryBuilder('p')
            ->leftJoin('p.artist', 'a')
            ->leftJoin('p.category', 'c')
            ->leftJoin('p.tags', 't')
            ->leftJoin('p.coverpic', 'cp')
            ->addSelect('a')
            ->addSelect('c')
            ->addSelect('t')
            ->addSelect('cp')
        ;
    }

    public function findOngoingProjects() {
        return $this->baseQueryBuilder()
            ->where('p.validated = 1 AND p.deletedAt IS NULL')
            ->andWhere('p.successful = 1 OR (p.successful = 0 AND p.failed = 0 AND p.refunded = 0)')
            ->andWhere('p.dateEnd >= :now')
            ->orderBy('p.dateEnd', 'ASC')
            ->setParameter('now', new \DateTime())
            ->getQuery()
            ->getResult()
            ;
    }

    public function findSuccessfulProjects() {
        return $this->baseQueryBuilder()
            ->where('p.validated = 1 AND p.deletedAt IS NULL')
            ->andWhere('p.successful = 1')
            ->andWhere('p.dateEnd < :now')
            ->orderBy('p.dateEnd', 'DESC')
            ->setParameter('now', new \DateTime())
            ->getQuery()
            ->getResult()
            ;
    }


    public function findPendingProjects() {
        return $this->createQueryBuilder('p')
            ->where('p.validated = 1 AND p.deletedAt IS NULL')
            ->andWhere('p.successful = 0 AND p.failed = 0 AND p.refunded = 0')
            ->andWhere('p.dateEnd < :now')
            ->setParameter('now', new \DateTime())
            ->getQuery()
            ->getResult()
        ;
    }


    public function getCurrentProjects(User $user) {
        return $this->createQueryBuilder('p')
            ->join('p.handlers', 'u')
            ->where('u.id = :id')
            ->andWhere('p.deletedAt IS NULL')
            ->andwhere('p.dateEnd >= :now OR (p.successful = 0 AND p.failed = 0)')
            ->orderBy('p.dateEnd', 'ASC')
            ->setParameter('id', $user->getId())
            ->setParameter('now', new \DateTime())
            ->getQuery()
            ->getResult()
        ;
    }

    public function getOtherCurrentProjects(User $user) {
        return $this->createQueryBuilder('p')
            ->join('p.handlers', 'u')
            ->where('u.id != :id')
            ->andWhere('p.deletedAt IS NULL')
            ->andwhere('p.dateEnd >= :now OR (p.successful = 0 AND p.failed = 0)')
            ->orderBy('p.dateEnd', 'ASC')
            ->setParameter('id', $user->getId())
            ->setParameter('now', new \DateTime())
            ->getQuery()
            ->getResult()
        ;
    }


    public function getPassedProjects(User $user) {
        return $this->createQueryBuilder('p')
            ->join('p.handlers', 'u')
            ->orderBy('p.dateEnd', 'DESC')
            ->where('u.id = :id')
            ->andWhere('p.validated = 1 AND p.deletedAt IS NULL')
            ->andWhere('p.successful = 1 OR p.failed = 1')
            ->andWhere('p.dateEnd < :now')
            ->setParameters([
                'id' => $user->getId(),
                'now' => new \DateTime()
            ])
            ->getQuery()
            ->getResult()
        ;
    }

    public function getOtherPassedProjects(User $user) {
        return $this->createQueryBuilder('p')
            ->join('p.handlers', 'u')
            ->orderBy('p.dateEnd', 'DESC')
            ->where('u.id != :id')
            ->andWhere('p.validated = 1 AND p.deletedAt IS NULL')
            ->andWhere('p.successful = 1 OR p.failed = 1')
            ->andWhere('p.dateEnd < :now')
            ->setParameters([
                'id' => $user->getId(),
                'now' => new \DateTime()
            ])
            ->getQuery()
            ->getResult()
        ;
    }


}
