<?php

namespace XBundle\Repository;

use AppBundle\Entity\User;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{

    public function getCurrentProjects($user = null) {
        return $this->createQueryBuilder('p')
            ->join('p.user', 'u')
            ->where('u.id = :id')
            ->andWhere('p.dateEnd >= :now')
            ->andWhere('p.failed = 0')
            ->orderBy('p.dateCreation', 'ASC')
            ->setParameters([
                'id' => $user->getId(),
                'now' => new \DateTime()
            ])
            ->getQuery()
            ->getResult()
        ;
    }


    public function getPassedProjects($user = null) {
        return $this->createQueryBuilder('p')
            ->join('p.user', 'u')
            ->orderBy('p.dateEnd', 'DESC')
            ->where('u.id = :id')
            ->andWhere('p.dateEnd < :now')
            /*->andWhere('p.failed = 1')*/
            ->setParameters([
                'id' => $user->getId(),
                'now' => new \DateTime()
            ])
            ->getQuery()
            ->getResult()
            ;
    }

}
