<?php

namespace XBundle\Repository;

/**
 * ProjectsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectsRepository extends \Doctrine\ORM\EntityRepository
{
}
