<?php

namespace XBundle\Repository;

/**
 * XCartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class XCartRepository extends \Doctrine\ORM\EntityRepository
{
}
