<?php

namespace XBundle\Repository;

use AppBundle\Entity\User;
use XBundle\Entity\Project;

/**
 * XCartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class XCartRepository extends \Doctrine\ORM\EntityRepository
{

    public function findUserDonations(User $user) {
        return $this->createQueryBuilder('xc')
            ->join('xc.contracts', 'cf')
            ->join('xc.order', 'xo')
            ->orderBy('cf.date', 'desc')
            ->where('xo.email = :email')
            ->andWhere('xc.confirmed = 1 AND xc.paid = 1')
            ->andWhere('cf.isDonation = 1')
            ->setParameter('email', $user->getEmail())
            ->getQuery()
            ->getResult()
        ;
    }

    public function findUserPurchases(User $user) {
        return $this->createQueryBuilder('xc')
            ->join('xc.contracts', 'cf')
            ->join('xc.order', 'xo')
            ->orderBy('cf.date', 'desc')
            ->where('xo.email = :email')
            ->andWhere('xc.confirmed = 1 AND xc.paid = 1')
            ->andWhere('cf.isDonation = 0')
            ->setParameter('email', $user->getEmail())
            ->getQuery()
            ->getResult()
        ;
    }


    public function getProjectCarts(Project $project) {
        return $this->createQueryBuilder('xc')
            ->join('xc.project', 'p')
            ->where('p.id = :id')
            ->setParameter('id', $project->getId())
            ->getQuery()
            ->getResult()
        ;
    }

}
