<?php

namespace XBundle\Repository;

/**
 * XCartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class XCartRepository extends \Doctrine\ORM\EntityRepository
{
    public function getProjectCarts($project) {
        return $this->createQueryBuilder('xc')
            ->join('xc.project', 'p')
            ->where('p.id = :id')
            ->setParameter('id', $project->getId())
            ->getQuery()
            ->getResult()
        ;
    }
}
