<?php

namespace XBundle\Repository;

/**
 * XCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class XCategoryRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * check if category is already in Chapots
     *
     * @param $category
     * @return mixed category name or null
     */
    public function categoryExists($category)
    {
        return $this->getEntityManager()->createQuery(
            'SELECT c
                  FROM XBundle:XCategory c
                  WHERE c.name = ?1
                  ')
            ->setParameter(1, $category)
            ->getOneOrNullResult();
    }
}
