<?php

namespace XBundle\Repository;

/**
 * XContractFanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class XContractFanRepository extends \Doctrine\ORM\EntityRepository
{
}
