<?php

namespace XBundle\Repository;

/**
 * XContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class XContactRepository extends \Doctrine\ORM\EntityRepository
{
}
