<?php

namespace XBundle\Repository;

/**
 * XOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class XOrderRepository extends \Doctrine\ORM\EntityRepository
{
    
}
