<?php

namespace XBundle\Repository;

/**
 * XPaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class XPaymentRepository extends \Doctrine\ORM\EntityRepository
{
}
