<?php

namespace XBundle\Repository;

/**
 * XPurchaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class XPurchaseRepository extends \Doctrine\ORM\EntityRepository
{
}
