<?php

namespace XBundle\Repository;

/**
 * XTicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class XTicketRepository extends \Doctrine\ORM\EntityRepository
{
}
