<?php

namespace XBundle\Repository;

/**
 * XTransactionalMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class XTransactionalMessageRepository extends \Doctrine\ORM\EntityRepository
{
}
